#!/bin/sh

alias c='clear'
alias g='git'
alias vi='vim'

alias df='df -h'
alias du='du -ch'
alias dus='for each in $(find . -maxdepth 1 -type d) ; do du -hs "$each" | head -n1; done | sort -rh'
alias dmesg='dmesg --color=auto'
alias diff="colordiff"
alias grep='grep --color=auto'

if ls --color -d . >/dev/null 2>&1; then  # GNU ls
  alias ls='ls -F -h --color=always -v --author --time-style=long-iso'
  alias l='ls -l -a'
fi

alias mkdir='mkdir -pv'
alias psg='ps auwx | grep'

# Enable aliases to be sudo’ed
alias sudo='sudo '

alias mdstat='cat /proc/mdstat'
alias ports='netstat -tulanp'
alias wget='wget -c'

alias sl='ls'
alias gti='git'

alias ack="rg"

alias .='cd ../'
alias ..='cd ../../'
alias ...='cd ../../../'
alias ....='cd ../../../../'

alias ssh='ssh -x'
alias ssy='ssh -CX -c arcfour,blowfish-cbc'
