#!/bin/sh

alias c='clear'
alias g='git'
alias vi='vim'

alias df='df -h'
alias du='du -ch'
alias dus='for each in $(find . -maxdepth 1 -type d) ; do du -hs "$each" | head -n1; done | sort -rh'
alias dmesg='dmesg --color=auto'
alias diff="$HOME/.colordiff"
alias grep='grep --color=auto'
alias ls='ls -hF --color=auto'
alias lsl='ls -halF --color=auto'
alias mkdir='mkdir -pv'
alias psg='ps auwx | grep'

# Enable aliases to be sudo’ed
alias sudo='sudo '

alias mdstat='cat /proc/mdstat'
alias ports='netstat -tulanp'
alias wget='wget -c'

alias sl='ls'
alias gti='git'

alias ack="rg"
alias e="$HOME/.e"
alias htop="$HOME/.htop"
alias smem="$HOME/.smem"

alias .='cd ../'
alias ..='cd ../../'
alias ...='cd ../../../'
alias ....='cd ../../../../'

alias ssh='ssh -x'
alias ssy='ssh -CX -c arcfour,blowfish-cbc'
