#!/bin/sh

# Enable aliases to be sudo’ed
alias sudo='sudo '

# Common Typos
alias sl='ls'
alias gti='git'

# Directorys
alias .='cd ../'
alias ..='cd ../../'
alias ...='cd ../../../'
alias ....='cd ../../../../'

# Extensions
alias df='df -h'
alias du='du -ch'
alias dmesg='dmesg --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

if ls --color -d . >/dev/null 2>&1; then  # GNU ls
  alias ls='ls -F -h --color=always -v --author --time-style=long-iso'
  alias l='ls -l -a'
fi

alias mkdir='mkdir -pv'
alias ssh='ssh -x'
alias ssy='ssh -CX'
alias wget='wget -c'

# Shortcuts
alias c='clear'
alias g='git'
alias vi='vim'

# Utilities
alias ack="rg"
alias dus='for each in $(find . -maxdepth 1 -type d) ; do du -hs "$each" | head -n1; done | sort -rh'
alias diff="colordiff"
alias lss="stat -c '%A %a %n' *"
alias mdstat='cat /proc/mdstat'
alias ports='netstat -tulanp'
alias psg='ps auwx | grep'
