#!/usr/bin/env bash

xcode-select --install

if ! type brew >/dev/null 2>&1; then
 echo "Brew is not installed, installing."
 ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

brew update
brew upgrade

# Save Homebrew’s installed location.
BREW_PREFIX=$(brew --prefix)

brew install coreutils
ln -s "${BREW_PREFIX}/bin/gsha256sum" "${BREW_PREFIX}/bin/sha256sum"

# Install some other useful utilities like `sponge`.
brew install moreutils
# Install GNU `find`, `locate`, `updatedb`, and `xargs`, `g`-prefixed.
brew install findutils
# Install GNU `sed`, overwriting the built-in `sed`.
brew install gnu-sed
# Install a modern version of Bash and ZSH
brew install bash
brew install bash-completion2
brew install zsh
brew install zsh-completions
sudo -s 'echo /usr/local/bin/zsh >> /etc/shells' && chsh -s /usr/local/bin/zsh

# Install `wget` with IRI support.
brew install wget

# Install GnuPG to enable PGP-signing commits.
brew install gnupg

# Install more recent versions of some macOS tools.
brew install vim
brew install grep
brew install openssh
brew install screen
brew install php
brew install gmp

# Install some CTF tools; see https://github.com/ctfs/write-ups.
brew install binutils
brew install nmap
brew install tcpflow
brew install tcpreplay
brew install tcptrace
brew install xz

# Install other useful binaries.
brew install bat
brew install fd
brew install git
brew install git-lfs

git config --global color.ui auto

# Git comes with diff-highlight, but isn't in the PATH
ln -sf "$(brew --prefix)/share/git-core/contrib/diff-highlight/diff-highlight" /usr/local/bin/diff-highlight

brew tap miserlou/loop https://github.com/Miserlou/Loop.git
brew install loop --HEAD

brew install mtr
brew install ncdu
brew install p7zip
brew install pigz
brew install pv
brew install rename
brew install ripgrep
brew install shellcheck
brew install ssh-copy-id
brew install tree

brew cask install \
visual-studio-code \
notion \
google-chrome \
firefox-developer-edition \
iterm2 \

git config --global core.editor 'code --wait'

# Remove outdated versions from the cellar.
brew cleanup
