#!/bin/sh
#

## EXTRAS ##
source "$HOME/.extras"

## THEME ##
BASE16_SHELL="$HOME/.config/base16-shell/"
[ -n "$PS1" ] && \
    [ -s "$BASE16_SHELL/profile_helper.sh" ] && \
        eval "$("$BASE16_SHELL/profile_helper.sh")"
BASE16_THEME="seti"

## ALIASES ##
source "$HOME/.aliases"

## TOOLS ##
export PATH=$HOME/.bin:$PATH

## VARIABLES ##
source "$HOME/.variables"
