#!/bin/sh

export BLOCKSIZE=M

## EDITOR ##
export EDITOR='vim'
export SVN_EDITOR='vim'
export VISUAL='vim'

## LESS ##
export LESSOPEN="| /usr/share/source-highlight/src-hilite-lesspipe.sh %s"
export LESS=' -R -N'

## MAIL ##
unset MAILCHECK

## TERMINAL ##
export IGNOREEOF="1"
export TERM=xterm-256color
stty stop ''; stty start '';
stty -ixon -ixoff
