#!/bin/sh

export BLOCKSIZE=M

## EDITOR ##
export EDITOR='vim'
export SVN_EDITOR='vim'
export VISUAL='vim'

## LANGUAGE ##
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

## LESS ##

if type lesspipe.sh >/dev/null 2>&1; then
  export LESSOPEN='|lesspipe.sh %s'
fi

if type pygmentize >/dev/null 2>&1; then
  export LESSCOLORIZER='pygmentize'
fi

## LS COLORS ##
eval "$(dircolors $HOME/.dircolors)"

## MAIL ##
unset MAILCHECK

## TERMINAL ##
export IGNOREEOF="1"
export TERM=xterm-256color
stty stop ''; stty start '';
stty -ixon -ixoff
